version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: blueflag/circle-node:0.0.9
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      # Add blueflag npm registry
      - run: echo "@blueflag:registry=https://$BLUEFLAG_NPM_REGISTRY_URL" >> ~/.npmrc
      - run: echo "always-auth=true" >> ~/.npmrc
      - run: echo "//$BLUEFLAG_NPM_REGISTRY_URL:_authToken=$BLUEFLAG_NPM_AUTH_TOKEN" >> ~/.npmrc
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      # run tests!
      - run: yarn test-all
      - run: git --no-pager diff && test -z "$(git status --porcelain)"
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
