// flow-typed signature: a61a8f0dc8b77942bb00c40454af1cda
// flow-typed version: <<STUB>>/babel-preset-blueflag_v^0.3.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-blueflag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-blueflag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-blueflag/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-blueflag/index' {
  declare module.exports: $Exports<'babel-preset-blueflag'>;
}
declare module 'babel-preset-blueflag/index.js' {
  declare module.exports: $Exports<'babel-preset-blueflag'>;
}
declare module 'babel-preset-blueflag/test.js' {
  declare module.exports: $Exports<'babel-preset-blueflag/test'>;
}
