// flow-typed signature: edc896803e8fcb496ea6feda81125294
// flow-typed version: <<STUB>>/browser-detect_v^0.2.28/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browser-detect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browser-detect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browser-detect/dist/browser-detect.es5' {
  declare module.exports: any;
}

declare module 'browser-detect/dist/browser-detect.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browser-detect/dist/browser-detect.es5.js' {
  declare module.exports: $Exports<'browser-detect/dist/browser-detect.es5'>;
}
declare module 'browser-detect/dist/browser-detect.umd.js' {
  declare module.exports: $Exports<'browser-detect/dist/browser-detect.umd'>;
}
