// flow-typed signature: 81ea195712910574c98072e8bd3e8a3d
// flow-typed version: <<STUB>>/fronads_v^0.6.4/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fronads'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fronads' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fronads/lib/__test__/Either-test' {
  declare module.exports: any;
}

declare module 'fronads/lib/__test__/Identity-test' {
  declare module.exports: any;
}

declare module 'fronads/lib/__test__/Maybe-test' {
  declare module.exports: any;
}

declare module 'fronads/lib/__test__/RequestState-test' {
  declare module.exports: any;
}

declare module 'fronads/lib/__test__/StateFunctor-test' {
  declare module.exports: any;
}

declare module 'fronads/lib/Either' {
  declare module.exports: any;
}

declare module 'fronads/lib/Identity' {
  declare module.exports: any;
}

declare module 'fronads/lib' {
  declare module.exports: any;
}

declare module 'fronads/lib/Maybe' {
  declare module.exports: any;
}

declare module 'fronads/lib/RequestState' {
  declare module.exports: any;
}

declare module 'fronads/lib/StateFunctor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fronads/lib/__test__/Either-test.js' {
  declare module.exports: $Exports<'fronads/lib/__test__/Either-test'>;
}
declare module 'fronads/lib/__test__/Identity-test.js' {
  declare module.exports: $Exports<'fronads/lib/__test__/Identity-test'>;
}
declare module 'fronads/lib/__test__/Maybe-test.js' {
  declare module.exports: $Exports<'fronads/lib/__test__/Maybe-test'>;
}
declare module 'fronads/lib/__test__/RequestState-test.js' {
  declare module.exports: $Exports<'fronads/lib/__test__/RequestState-test'>;
}
declare module 'fronads/lib/__test__/StateFunctor-test.js' {
  declare module.exports: $Exports<'fronads/lib/__test__/StateFunctor-test'>;
}
declare module 'fronads/lib/Either.js' {
  declare module.exports: $Exports<'fronads/lib/Either'>;
}
declare module 'fronads/lib/Identity.js' {
  declare module.exports: $Exports<'fronads/lib/Identity'>;
}
declare module 'fronads/lib/index' {
  declare module.exports: $Exports<'fronads/lib'>;
}
declare module 'fronads/lib/index.js' {
  declare module.exports: $Exports<'fronads/lib'>;
}
declare module 'fronads/lib/Maybe.js' {
  declare module.exports: $Exports<'fronads/lib/Maybe'>;
}
declare module 'fronads/lib/RequestState.js' {
  declare module.exports: $Exports<'fronads/lib/RequestState'>;
}
declare module 'fronads/lib/StateFunctor.js' {
  declare module.exports: $Exports<'fronads/lib/StateFunctor'>;
}
