// flow-typed signature: e7339cf3ac6e5b98b364323a51afa6cc
// flow-typed version: <<STUB>>/goose-css_vv0.12.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'goose-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'goose-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'goose-css/index' {
  declare module.exports: $Exports<'goose-css'>;
}
declare module 'goose-css/index.js' {
  declare module.exports: $Exports<'goose-css'>;
}
