// flow-typed signature: 43ef70326d800b5bfaf4c43d608528d1
// flow-typed version: <<STUB>>/obtuse_v^0.6.1/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'obtuse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'obtuse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'obtuse/lib/component/Code' {
  declare module.exports: any;
}

declare module 'obtuse/lib/component/Paragraph' {
  declare module.exports: any;
}

declare module 'obtuse/lib/component/Text' {
  declare module.exports: any;
}

declare module 'obtuse/lib/icon/Icon' {
  declare module.exports: any;
}

declare module 'obtuse/lib' {
  declare module.exports: any;
}

declare module 'obtuse/lib/molecule/FieldRow' {
  declare module.exports: any;
}

declare module 'obtuse/lib/molecule/Message' {
  declare module.exports: any;
}

// Filename aliases
declare module 'obtuse/lib/component/Code.js' {
  declare module.exports: $Exports<'obtuse/lib/component/Code'>;
}
declare module 'obtuse/lib/component/Paragraph.js' {
  declare module.exports: $Exports<'obtuse/lib/component/Paragraph'>;
}
declare module 'obtuse/lib/component/Text.js' {
  declare module.exports: $Exports<'obtuse/lib/component/Text'>;
}
declare module 'obtuse/lib/icon/Icon.js' {
  declare module.exports: $Exports<'obtuse/lib/icon/Icon'>;
}
declare module 'obtuse/lib/index' {
  declare module.exports: $Exports<'obtuse/lib'>;
}
declare module 'obtuse/lib/index.js' {
  declare module.exports: $Exports<'obtuse/lib'>;
}
declare module 'obtuse/lib/molecule/FieldRow.js' {
  declare module.exports: $Exports<'obtuse/lib/molecule/FieldRow'>;
}
declare module 'obtuse/lib/molecule/Message.js' {
  declare module.exports: $Exports<'obtuse/lib/molecule/Message'>;
}
