// flow-typed signature: cb9fb3f27d28789cef9120b3bc57f890
// flow-typed version: <<STUB>>/pipwerks-scorm-api-wrapper_v^0.1.2/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pipwerks-scorm-api-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pipwerks-scorm-api-wrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pipwerks-scorm-api-wrapper/src' {
  declare module.exports: any;
}

declare module 'pipwerks-scorm-api-wrapper/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pipwerks-scorm-api-wrapper/index' {
  declare module.exports: $Exports<'pipwerks-scorm-api-wrapper'>;
}
declare module 'pipwerks-scorm-api-wrapper/index.js' {
  declare module.exports: $Exports<'pipwerks-scorm-api-wrapper'>;
}
declare module 'pipwerks-scorm-api-wrapper/src/index' {
  declare module.exports: $Exports<'pipwerks-scorm-api-wrapper/src'>;
}
declare module 'pipwerks-scorm-api-wrapper/src/index.js' {
  declare module.exports: $Exports<'pipwerks-scorm-api-wrapper/src'>;
}
declare module 'pipwerks-scorm-api-wrapper/webpack.config.js' {
  declare module.exports: $Exports<'pipwerks-scorm-api-wrapper/webpack.config'>;
}
