// flow-typed signature: 3ae7d697de25c86782638c81d1be79fe
// flow-typed version: <<STUB>>/react-showdown_v^1.6.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-showdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-showdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-showdown/lib/Converter' {
  declare module.exports: any;
}

declare module 'react-showdown/lib/Element' {
  declare module.exports: any;
}

declare module 'react-showdown/lib' {
  declare module.exports: any;
}

declare module 'react-showdown/test/ConverterTest' {
  declare module.exports: any;
}

declare module 'react-showdown/test/ElementTest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-showdown/lib/Converter.js' {
  declare module.exports: $Exports<'react-showdown/lib/Converter'>;
}
declare module 'react-showdown/lib/Element.js' {
  declare module.exports: $Exports<'react-showdown/lib/Element'>;
}
declare module 'react-showdown/lib/index' {
  declare module.exports: $Exports<'react-showdown/lib'>;
}
declare module 'react-showdown/lib/index.js' {
  declare module.exports: $Exports<'react-showdown/lib'>;
}
declare module 'react-showdown/test/ConverterTest.js' {
  declare module.exports: $Exports<'react-showdown/test/ConverterTest'>;
}
declare module 'react-showdown/test/ElementTest.js' {
  declare module.exports: $Exports<'react-showdown/test/ElementTest'>;
}
