// flow-typed signature: d0fa8a8a3a11f3e9ec2a4b1a8383b7dd
// flow-typed version: <<STUB>>/react-markdown-quiz_v^0.7.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-markdown-quiz'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-markdown-quiz' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-markdown-quiz/lib/checkHash' {
  declare module.exports: any;
}

declare module 'react-markdown-quiz/lib' {
  declare module.exports: any;
}

declare module 'react-markdown-quiz/lib/parseMarkdownQuiz' {
  declare module.exports: any;
}

declare module 'react-markdown-quiz/lib/parseQuiz' {
  declare module.exports: any;
}

declare module 'react-markdown-quiz/lib/quiz-loader' {
  declare module.exports: any;
}

declare module 'react-markdown-quiz/lib/Quiz' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-markdown-quiz/lib/checkHash.js' {
  declare module.exports: $Exports<'react-markdown-quiz/lib/checkHash'>;
}
declare module 'react-markdown-quiz/lib/index' {
  declare module.exports: $Exports<'react-markdown-quiz/lib'>;
}
declare module 'react-markdown-quiz/lib/index.js' {
  declare module.exports: $Exports<'react-markdown-quiz/lib'>;
}
declare module 'react-markdown-quiz/lib/parseMarkdownQuiz.js' {
  declare module.exports: $Exports<'react-markdown-quiz/lib/parseMarkdownQuiz'>;
}
declare module 'react-markdown-quiz/lib/parseQuiz.js' {
  declare module.exports: $Exports<'react-markdown-quiz/lib/parseQuiz'>;
}
declare module 'react-markdown-quiz/lib/quiz-loader.js' {
  declare module.exports: $Exports<'react-markdown-quiz/lib/quiz-loader'>;
}
declare module 'react-markdown-quiz/lib/Quiz.js' {
  declare module.exports: $Exports<'react-markdown-quiz/lib/Quiz'>;
}
