// flow-typed signature: 6acf1807d5c90ddcdbd64e01d72802f0
// flow-typed version: <<STUB>>/stampy_v^0.37.2/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stampy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stampy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stampy/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'stampy/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'stampy/example/dist/bundle' {
  declare module.exports: any;
}

declare module 'stampy/example/webpack.config' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/__test__/Button-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/__test__/Input-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/__test__/Label-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/__test__/Select-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/__test__/ShowHide-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/__test__/Table-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/__test__/Text-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/__test__/Textarea-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/__test__/Toggle-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/__test__/ToggleSet-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/Button' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/Input' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/Label' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/Select' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/ShowHide' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/Table' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/Text' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/Textarea' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/Toggle' {
  declare module.exports: any;
}

declare module 'stampy/lib/component/ToggleSet' {
  declare module.exports: any;
}

declare module 'stampy/lib/decls/FlowTypes' {
  declare module.exports: any;
}

declare module 'stampy/lib/decls/JsdocTypes' {
  declare module.exports: any;
}

declare module 'stampy/lib/deprecated/pipe/__test__/DebouncePipe-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/deprecated/pipe/__test__/DownPipe-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/deprecated/pipe/__test__/SplitIndexPipe-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/deprecated/pipe/__test__/SplitKeyPipe-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/deprecated/pipe/__test__/SpreadPipe-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/deprecated/pipe/__test__/UpPipe-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/deprecated/pipe/DebouncePipe' {
  declare module.exports: any;
}

declare module 'stampy/lib/deprecated/pipe/DownPipe' {
  declare module.exports: any;
}

declare module 'stampy/lib/deprecated/pipe/SplitIndexPipe' {
  declare module.exports: any;
}

declare module 'stampy/lib/deprecated/pipe/SplitKeyPipe' {
  declare module.exports: any;
}

declare module 'stampy/lib/deprecated/pipe/SpreadPipe' {
  declare module.exports: any;
}

declare module 'stampy/lib/deprecated/pipe/UpPipe' {
  declare module.exports: any;
}

declare module 'stampy/lib/deprecated/util/__test__/CollectionUtils-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/deprecated/util/__test__/ConfigureHock-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/deprecated/util/CollectionUtils' {
  declare module.exports: any;
}

declare module 'stampy/lib/deprecated/util/ConfigureHock' {
  declare module.exports: any;
}

declare module 'stampy/lib/element/__test__/ChildOf-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/element/__test__/PropsOf-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/element/ChildOf' {
  declare module.exports: any;
}

declare module 'stampy/lib/element/PropsOf' {
  declare module.exports: any;
}

declare module 'stampy/lib/hock/__test__/ElementQueryHock-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/hock/__test__/ElementQueryHockServerSide-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/hock/__test__/PropChangeHock-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/hock/__test__/QueryStringHock-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/hock/__test__/StateHock-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/hock/ElementQueryHock' {
  declare module.exports: any;
}

declare module 'stampy/lib/hock/PropChangeHock' {
  declare module.exports: any;
}

declare module 'stampy/lib/hock/QueryStringHock' {
  declare module.exports: any;
}

declare module 'stampy/lib/hock/StateHock' {
  declare module.exports: any;
}

declare module 'stampy/lib/util/__test__/Compose-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/util/__test__/Hock-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/util/__test__/SpruceClassName-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/util/__test__/SpruceComponent-test' {
  declare module.exports: any;
}

declare module 'stampy/lib/util/Compose' {
  declare module.exports: any;
}

declare module 'stampy/lib/util/Hock' {
  declare module.exports: any;
}

declare module 'stampy/lib/util/SpruceClassName' {
  declare module.exports: any;
}

declare module 'stampy/lib/util/SpruceComponent' {
  declare module.exports: any;
}

declare module 'stampy/scripts/publish' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stampy/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'stampy/coverage/lcov-report/prettify'>;
}
declare module 'stampy/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'stampy/coverage/lcov-report/sorter'>;
}
declare module 'stampy/example/dist/bundle.js' {
  declare module.exports: $Exports<'stampy/example/dist/bundle'>;
}
declare module 'stampy/example/webpack.config.js' {
  declare module.exports: $Exports<'stampy/example/webpack.config'>;
}
declare module 'stampy/lib/component/__test__/Button-test.js' {
  declare module.exports: $Exports<'stampy/lib/component/__test__/Button-test'>;
}
declare module 'stampy/lib/component/__test__/Input-test.js' {
  declare module.exports: $Exports<'stampy/lib/component/__test__/Input-test'>;
}
declare module 'stampy/lib/component/__test__/Label-test.js' {
  declare module.exports: $Exports<'stampy/lib/component/__test__/Label-test'>;
}
declare module 'stampy/lib/component/__test__/Select-test.js' {
  declare module.exports: $Exports<'stampy/lib/component/__test__/Select-test'>;
}
declare module 'stampy/lib/component/__test__/ShowHide-test.js' {
  declare module.exports: $Exports<'stampy/lib/component/__test__/ShowHide-test'>;
}
declare module 'stampy/lib/component/__test__/Table-test.js' {
  declare module.exports: $Exports<'stampy/lib/component/__test__/Table-test'>;
}
declare module 'stampy/lib/component/__test__/Text-test.js' {
  declare module.exports: $Exports<'stampy/lib/component/__test__/Text-test'>;
}
declare module 'stampy/lib/component/__test__/Textarea-test.js' {
  declare module.exports: $Exports<'stampy/lib/component/__test__/Textarea-test'>;
}
declare module 'stampy/lib/component/__test__/Toggle-test.js' {
  declare module.exports: $Exports<'stampy/lib/component/__test__/Toggle-test'>;
}
declare module 'stampy/lib/component/__test__/ToggleSet-test.js' {
  declare module.exports: $Exports<'stampy/lib/component/__test__/ToggleSet-test'>;
}
declare module 'stampy/lib/component/Button.js' {
  declare module.exports: $Exports<'stampy/lib/component/Button'>;
}
declare module 'stampy/lib/component/Input.js' {
  declare module.exports: $Exports<'stampy/lib/component/Input'>;
}
declare module 'stampy/lib/component/Label.js' {
  declare module.exports: $Exports<'stampy/lib/component/Label'>;
}
declare module 'stampy/lib/component/Select.js' {
  declare module.exports: $Exports<'stampy/lib/component/Select'>;
}
declare module 'stampy/lib/component/ShowHide.js' {
  declare module.exports: $Exports<'stampy/lib/component/ShowHide'>;
}
declare module 'stampy/lib/component/Table.js' {
  declare module.exports: $Exports<'stampy/lib/component/Table'>;
}
declare module 'stampy/lib/component/Text.js' {
  declare module.exports: $Exports<'stampy/lib/component/Text'>;
}
declare module 'stampy/lib/component/Textarea.js' {
  declare module.exports: $Exports<'stampy/lib/component/Textarea'>;
}
declare module 'stampy/lib/component/Toggle.js' {
  declare module.exports: $Exports<'stampy/lib/component/Toggle'>;
}
declare module 'stampy/lib/component/ToggleSet.js' {
  declare module.exports: $Exports<'stampy/lib/component/ToggleSet'>;
}
declare module 'stampy/lib/decls/FlowTypes.js' {
  declare module.exports: $Exports<'stampy/lib/decls/FlowTypes'>;
}
declare module 'stampy/lib/decls/JsdocTypes.js' {
  declare module.exports: $Exports<'stampy/lib/decls/JsdocTypes'>;
}
declare module 'stampy/lib/deprecated/pipe/__test__/DebouncePipe-test.js' {
  declare module.exports: $Exports<'stampy/lib/deprecated/pipe/__test__/DebouncePipe-test'>;
}
declare module 'stampy/lib/deprecated/pipe/__test__/DownPipe-test.js' {
  declare module.exports: $Exports<'stampy/lib/deprecated/pipe/__test__/DownPipe-test'>;
}
declare module 'stampy/lib/deprecated/pipe/__test__/SplitIndexPipe-test.js' {
  declare module.exports: $Exports<'stampy/lib/deprecated/pipe/__test__/SplitIndexPipe-test'>;
}
declare module 'stampy/lib/deprecated/pipe/__test__/SplitKeyPipe-test.js' {
  declare module.exports: $Exports<'stampy/lib/deprecated/pipe/__test__/SplitKeyPipe-test'>;
}
declare module 'stampy/lib/deprecated/pipe/__test__/SpreadPipe-test.js' {
  declare module.exports: $Exports<'stampy/lib/deprecated/pipe/__test__/SpreadPipe-test'>;
}
declare module 'stampy/lib/deprecated/pipe/__test__/UpPipe-test.js' {
  declare module.exports: $Exports<'stampy/lib/deprecated/pipe/__test__/UpPipe-test'>;
}
declare module 'stampy/lib/deprecated/pipe/DebouncePipe.js' {
  declare module.exports: $Exports<'stampy/lib/deprecated/pipe/DebouncePipe'>;
}
declare module 'stampy/lib/deprecated/pipe/DownPipe.js' {
  declare module.exports: $Exports<'stampy/lib/deprecated/pipe/DownPipe'>;
}
declare module 'stampy/lib/deprecated/pipe/SplitIndexPipe.js' {
  declare module.exports: $Exports<'stampy/lib/deprecated/pipe/SplitIndexPipe'>;
}
declare module 'stampy/lib/deprecated/pipe/SplitKeyPipe.js' {
  declare module.exports: $Exports<'stampy/lib/deprecated/pipe/SplitKeyPipe'>;
}
declare module 'stampy/lib/deprecated/pipe/SpreadPipe.js' {
  declare module.exports: $Exports<'stampy/lib/deprecated/pipe/SpreadPipe'>;
}
declare module 'stampy/lib/deprecated/pipe/UpPipe.js' {
  declare module.exports: $Exports<'stampy/lib/deprecated/pipe/UpPipe'>;
}
declare module 'stampy/lib/deprecated/util/__test__/CollectionUtils-test.js' {
  declare module.exports: $Exports<'stampy/lib/deprecated/util/__test__/CollectionUtils-test'>;
}
declare module 'stampy/lib/deprecated/util/__test__/ConfigureHock-test.js' {
  declare module.exports: $Exports<'stampy/lib/deprecated/util/__test__/ConfigureHock-test'>;
}
declare module 'stampy/lib/deprecated/util/CollectionUtils.js' {
  declare module.exports: $Exports<'stampy/lib/deprecated/util/CollectionUtils'>;
}
declare module 'stampy/lib/deprecated/util/ConfigureHock.js' {
  declare module.exports: $Exports<'stampy/lib/deprecated/util/ConfigureHock'>;
}
declare module 'stampy/lib/element/__test__/ChildOf-test.js' {
  declare module.exports: $Exports<'stampy/lib/element/__test__/ChildOf-test'>;
}
declare module 'stampy/lib/element/__test__/PropsOf-test.js' {
  declare module.exports: $Exports<'stampy/lib/element/__test__/PropsOf-test'>;
}
declare module 'stampy/lib/element/ChildOf.js' {
  declare module.exports: $Exports<'stampy/lib/element/ChildOf'>;
}
declare module 'stampy/lib/element/PropsOf.js' {
  declare module.exports: $Exports<'stampy/lib/element/PropsOf'>;
}
declare module 'stampy/lib/hock/__test__/ElementQueryHock-test.js' {
  declare module.exports: $Exports<'stampy/lib/hock/__test__/ElementQueryHock-test'>;
}
declare module 'stampy/lib/hock/__test__/ElementQueryHockServerSide-test.js' {
  declare module.exports: $Exports<'stampy/lib/hock/__test__/ElementQueryHockServerSide-test'>;
}
declare module 'stampy/lib/hock/__test__/PropChangeHock-test.js' {
  declare module.exports: $Exports<'stampy/lib/hock/__test__/PropChangeHock-test'>;
}
declare module 'stampy/lib/hock/__test__/QueryStringHock-test.js' {
  declare module.exports: $Exports<'stampy/lib/hock/__test__/QueryStringHock-test'>;
}
declare module 'stampy/lib/hock/__test__/StateHock-test.js' {
  declare module.exports: $Exports<'stampy/lib/hock/__test__/StateHock-test'>;
}
declare module 'stampy/lib/hock/ElementQueryHock.js' {
  declare module.exports: $Exports<'stampy/lib/hock/ElementQueryHock'>;
}
declare module 'stampy/lib/hock/PropChangeHock.js' {
  declare module.exports: $Exports<'stampy/lib/hock/PropChangeHock'>;
}
declare module 'stampy/lib/hock/QueryStringHock.js' {
  declare module.exports: $Exports<'stampy/lib/hock/QueryStringHock'>;
}
declare module 'stampy/lib/hock/StateHock.js' {
  declare module.exports: $Exports<'stampy/lib/hock/StateHock'>;
}
declare module 'stampy/lib/util/__test__/Compose-test.js' {
  declare module.exports: $Exports<'stampy/lib/util/__test__/Compose-test'>;
}
declare module 'stampy/lib/util/__test__/Hock-test.js' {
  declare module.exports: $Exports<'stampy/lib/util/__test__/Hock-test'>;
}
declare module 'stampy/lib/util/__test__/SpruceClassName-test.js' {
  declare module.exports: $Exports<'stampy/lib/util/__test__/SpruceClassName-test'>;
}
declare module 'stampy/lib/util/__test__/SpruceComponent-test.js' {
  declare module.exports: $Exports<'stampy/lib/util/__test__/SpruceComponent-test'>;
}
declare module 'stampy/lib/util/Compose.js' {
  declare module.exports: $Exports<'stampy/lib/util/Compose'>;
}
declare module 'stampy/lib/util/Hock.js' {
  declare module.exports: $Exports<'stampy/lib/util/Hock'>;
}
declare module 'stampy/lib/util/SpruceClassName.js' {
  declare module.exports: $Exports<'stampy/lib/util/SpruceClassName'>;
}
declare module 'stampy/lib/util/SpruceComponent.js' {
  declare module.exports: $Exports<'stampy/lib/util/SpruceComponent'>;
}
declare module 'stampy/scripts/publish.js' {
  declare module.exports: $Exports<'stampy/scripts/publish'>;
}
