// flow-typed signature: fc21d5df9c84ba7462da90c0fed250eb
// flow-typed version: <<STUB>>/@blueflag/proto-blueflag-test_v^0.10.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@blueflag/proto-blueflag-test'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@blueflag/proto-blueflag-test' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@blueflag/proto-blueflag-test/lib/config/pretest' {
  declare module.exports: any;
}

declare module '@blueflag/proto-blueflag-test/lib/coverage' {
  declare module.exports: any;
}

declare module '@blueflag/proto-blueflag-test/lib/flow-test' {
  declare module.exports: any;
}

declare module '@blueflag/proto-blueflag-test/lib/flow' {
  declare module.exports: any;
}

declare module '@blueflag/proto-blueflag-test/lib' {
  declare module.exports: any;
}

declare module '@blueflag/proto-blueflag-test/lib/lint-test' {
  declare module.exports: any;
}

declare module '@blueflag/proto-blueflag-test/lib/lint' {
  declare module.exports: any;
}

declare module '@blueflag/proto-blueflag-test/lib/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@blueflag/proto-blueflag-test/lib/config/pretest.js' {
  declare module.exports: $Exports<'@blueflag/proto-blueflag-test/lib/config/pretest'>;
}
declare module '@blueflag/proto-blueflag-test/lib/coverage.js' {
  declare module.exports: $Exports<'@blueflag/proto-blueflag-test/lib/coverage'>;
}
declare module '@blueflag/proto-blueflag-test/lib/flow-test.js' {
  declare module.exports: $Exports<'@blueflag/proto-blueflag-test/lib/flow-test'>;
}
declare module '@blueflag/proto-blueflag-test/lib/flow.js' {
  declare module.exports: $Exports<'@blueflag/proto-blueflag-test/lib/flow'>;
}
declare module '@blueflag/proto-blueflag-test/lib/index' {
  declare module.exports: $Exports<'@blueflag/proto-blueflag-test/lib'>;
}
declare module '@blueflag/proto-blueflag-test/lib/index.js' {
  declare module.exports: $Exports<'@blueflag/proto-blueflag-test/lib'>;
}
declare module '@blueflag/proto-blueflag-test/lib/lint-test.js' {
  declare module.exports: $Exports<'@blueflag/proto-blueflag-test/lib/lint-test'>;
}
declare module '@blueflag/proto-blueflag-test/lib/lint.js' {
  declare module.exports: $Exports<'@blueflag/proto-blueflag-test/lib/lint'>;
}
declare module '@blueflag/proto-blueflag-test/lib/test.js' {
  declare module.exports: $Exports<'@blueflag/proto-blueflag-test/lib/test'>;
}
